### PR TITLE
Stream Messages

### PR DESCRIPTION
**Pull request by tpreusse**
Add an option to stream messages. This should permit processing of messages larger than the V8 string length limit. See #7

### CODE REVIEW

**Comment by robertklep** [comment]
Awesome, thanks! I'll take a closer look at it ASAP.

**Comment by tpreusse** [comment]
Cool. No rush, just felt like giving it a shot yesterday evening.

I'm not 100% solid on node streams, do we need to pause (when `!messageStream.push()`) and resume (on `messageStream._read`) the input stream (`handle`)?

**Comment by tpreusse** [comment]
Tried it on some real world examples and doesn't work as expected.

Specifically mailparser didn't always end. Not sure if I implemented something wrong with the readable streams or if it's a mailparser issue.

Anyhow I think it shouldn't be merged as is. I ended up using a different approach with just [`split`](https://gist.github.com/tpreusse/0649ef084d433356c87c4980343e177b).

**Comment by robertklep** [comment]
@tpreusse the idea of being able to pass around a stream (instead of a string) still seems like a reasonable option to me (although good to know that you got it working with an alternative).

**Comment by robertklep** [comment]
@tpreusse I just pushed a separate branch with basically a rewrite of the module, including streaming. If you want, you can test it yourself:

```
$ npm i robertklep/node-mbox#v1
```

Example code:
```
const { simpleParser } = require('mailparser');
const Mbox             = require('node-mbox');
const mbox             = new Mbox({ stream : true });

mbox.on('message', function(stream) {
  simpleParser(stream).then(mail => {
    console.log('From   :', mail.headers.get('from').value[0].address);
    console.log('Subject:', mail.headers.get('subject'), '\n');
  }).catch(e => {
    console.error('Error parsing e-mail');
    console.error(e);
  });
});

process.stdin.pipe(mbox);
```

Be aware that the `message` events will not wait for the parser to finish. I haven't yet looked at pausing/resuming.

**Comment by tpreusse** [comment]
@robertklep looks very nice – tested it on two mboxes—including the one with messages over 260mb—and worked perfectly.

Here is how I'm using it:
https://github.com/tpreusse/mbox-utils/blob/master/extract-mbox.js

I am using `stream.on('data')` and `stream.on('end')` to write the data to two streams.

**Comment by robertklep** [comment]
Thanks for testing, @tpreusse 👍 

I'll clean up the documentation and release it as `node-mbox@1.0.0`.

**Comment by robertklep** [comment]
@tpreusse  just pushed `node-mbox@1.0.0` to the NPM repository.

**Pull request closed without merging**
