### PR TITLE
Upgrade to v2.0.0.

### PR DESCRIPTION
**Pull request by mafiosso**
Hi we use your node-mbox however it was hard to handle finish for async tasks. It is due to misconception of on('message') and on('data') events. Now mbox is passing on 'data' the message itself - it is instance of Transform stream today. No 'message' event is present. This pull request is to discuss, I have changed API a lot and purged some functionality - explicit encoding, strict mode is now always on, passing Mbox header is now optional.

### CODE REVIEW

**Comment by robertklep** [comment]
Hi @mafiosso! Thanks a lot for your effort :) Are you okay with squashing the commits into a single one? Makes it easier for me to see what's going on and to comment.

**Comment by ghost** [comment]
@mafiosso

Definitely agree with the `strict` mode being on by default. I got burnt by that today, when it's `false` the stream just closes with no warning or error. I was using a few files with a strange encoding, unbeknownst to me, and was scratching my head over why the pipe kept closing on certain files.

@robertklep 
Also you can view all changes in the pull request at once by using the new Files Changed tab options and selecting **Show All Changes**, it will show entire file content and changes. There are a couple other cool options too. His commits are pretty siloed based on implemented functionality.

I can still squash the commits if it makes it easier. It would be good to get an update out on this, I don't mind spending some time helping. Repo is still going strong after all these years.

image

**Comment by robertklep** [comment]
@mafiosso would you be willing to accept ownership of this package on NPM? I can't spend time on this at the moment, and besides that, I haven't used this module myself for years.

**Comment by mafiosso** [comment]
Hi @robertklep thank you for your bid, sorry for I've never answered and never squashed the commits. Honestly I do not take care of it very much these times. But we internally depend on my fork. It would be nice to be owner of the NPM package. My npmjs user is this (https://www.npmjs.com/~mafiosso).

**Comment by robertklep** [comment]
@mafiosso there you go 😊

**Comment by mafiosso** [comment]
Thanks :).

**Pull request closed without merging**
